%Start of master_function.m file
diary log_roi_linear_cautious_SVM_boys_vs_girls.txt;feb13_2017_roi_linear_cautious_boys_vs_girls;clear all;
diary log_roi_linear_cautious_SVM_ctrls_vs_pts.txt;feb13_2017_roi_linear_cautious_controls_vs_patients;clear all;
diary log_roi_RBF_cautious_SVM_boys_vs_girls.txt;feb13_2017_roi_RBF_cautious_boys_vs_girls;clear all;
diary log_roi_RBF_cautious_SVM_ctrls_vs_pts.txt;feb13_2017_roi_RBF_cautious_controls_vs_patients;clear all;
diary log_roi_morlet_cautious_SVM_boys_vs_girls.txt;feb13_2017_roi_morlet_cautious_boys_vs_girls;clear all;
diary log_roi_morlet_cautious_SVM_ctrls_vs_pts.txt;feb13_2017_roi_morlet_cautious_controls_vs_patients;clear all;
diary log_roi_mexicanhat_cautious_SVM_boys_vs_girls.txt;feb13_2017_roi_mexicanhat_cautious_boys_vs_girls;clear all;
diary log_roi_mexicanhat_cautious_SVM_ctrls_vs_pts.txt;feb13_2017_roi_mexicanhat_cautious_controls_vs_patients;clear all;
diary log_roi_multiscalemexicanhat_cautious_SVM_boys_vs_girls.txt;feb13_2017_roi_multiscalemexicanhat_cautious_boys_vs_girls;clear all;
diary log_roi_multiscalemexicanhat_cautious_SVM_ctrls_vs_pts.txt;feb13_2017_roi_multiscalemexicanhat_cautious_controls_vs_patients;clear all;
%End of master_function.m file