%Start of master_function.m file
%diary log_striatum_RBF_risky_SVM_boys_vs_girls.txt;feb16_2017_striatum_RBF_risky_boys_vs_girls;clear all;
%diary log_striatum_RBF_risky_SVM_ctrls_vs_pts.txt;feb16_2017_striatum_RBF_risky_controls_vs_patients;clear all;
%diary log_striatum_RBF_cautious_SVM_boys_vs_girls.txt;feb16_2017_striatum_RBF_cautious_boys_vs_girls;clear all;
%diary log_striatum_RBF_cautious_SVM_ctrls_vs_pts.txt;feb16_2017_striatum_RBF_cautious_controls_vs_patients;clear all;
%diary log_striatum_morlet_risky_SVM_boys_vs_girls.txt;feb16_2017_striatum_morlet_risky_boys_vs_girls;clear all;
%diary log_striatum_morlet_risky_SVM_ctrls_vs_pts.txt;feb16_2017_striatum_morlet_risky_controls_vs_patients;clear all;
%diary log_striatum_morlet_cautious_SVM_boys_vs_girls.txt;feb16_2017_striatum_morlet_cautious_boys_vs_girls;clear all;
%diary log_striatum_morlet_cautious_SVM_ctrls_vs_pts.txt;feb16_2017_striatum_morlet_cautious_controls_vs_patients;clear all;
diary log_striatum_mexicanhat_risky_SVM_boys_vs_girls.txt;feb16_2017_striatum_mexicanhat_risky_boys_vs_girls;clear all;
diary log_striatum_mexicanhat_risky_SVM_ctrls_vs_pts.txt;feb16_2017_striatum_mexicanhat_risky_controls_vs_patients;clear all;
diary log_striatum_mexicanhat_cautious_SVM_boys_vs_girls.txt;feb16_2017_striatum_mexicanhat_cautious_boys_vs_girls;clear all;
diary log_striatum_mexicanhat_cautious_SVM_ctrls_vs_pts.txt;feb16_2017_striatum_mexicanhat_cautious_controls_vs_patients;clear all;
%diary log_striatum_multiscalemexicanhat_risky_SVM_boys_vs_girls.txt;feb16_2017_striatum_multiscalemexicanhat_risky_boys_vs_girls;clear all;
%diary log_striatum_multiscalemexicanhat_risky_SVM_ctrls_vs_pts.txt;feb16_2017_striatum_multiscalemexicanhat_risky_ctrls_vs_pts;clear all;
%diary log_striatum_multiscalemexicanhat_cautious_SVM_boys_vs_girls.txt;feb16_2017_striatum_multiscalemexicanhat_cautious_boys_vs_girls;clear all;
%diary log_striatum_multiscalemexicanhat_cautious_SVM_ctrls_vs_pts.txt;feb16_2017_striatum_multiscalemexicanhat_cautious_ctrls_vs_pts;clear all;
%End of master_function.m file
